
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'exprleftADDSUBleftMULDIVrightPOWrightUMINUSADD DIV LPAREN MUL NUM POW RPAREN SUBexpr : expr ADD termexpr : expr SUB termexpr : termterm : term MUL powerterm : term DIV powerterm : powerpower : unarypower : unary POW expNoPowunary : SUB unary %prec UMINUSunary : atomatom : NUMatom : LPAREN expr RPARENexpNoPow : expTermexpNoPow : expNoPow ADD expTermexpNoPow : expNoPow SUB expTermexpTerm : expUnaryexpTerm : expTerm MUL expUnaryexpTerm : expTerm DIV expUnaryexpUnary : SUB expUnary %prec UMINUSexpUnary : expAtomexpAtom : NUMexpAtom : LPAREN expNoPow RPAREN'
    
_lr_action_items = {'SUB':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[3,10,-3,3,-6,-7,-10,-11,3,3,3,3,3,-9,22,10,-1,-2,-4,-5,-8,-13,22,-16,-20,-21,22,-12,22,22,22,22,-19,29,-14,-15,-17,-18,-22,]),'NUM':([0,3,8,9,10,11,12,14,22,26,28,29,30,31,],[7,7,7,7,7,7,7,25,25,25,25,25,25,25,]),'LPAREN':([0,3,8,9,10,11,12,14,22,26,28,29,30,31,],[8,8,8,8,8,8,8,26,26,26,26,26,26,26,]),'$end':([1,2,4,5,6,7,13,16,17,18,19,20,21,23,24,25,27,32,34,35,36,37,38,],[0,-3,-6,-7,-10,-11,-9,-1,-2,-4,-5,-8,-13,-16,-20,-21,-12,-19,-14,-15,-17,-18,-22,]),'ADD':([1,2,4,5,6,7,13,15,16,17,18,19,20,21,23,24,25,27,32,33,34,35,36,37,38,],[9,-3,-6,-7,-10,-11,-9,9,-1,-2,-4,-5,-8,-13,-16,-20,-21,-12,-19,28,-14,-15,-17,-18,-22,]),'RPAREN':([2,4,5,6,7,13,15,16,17,18,19,20,21,23,24,25,27,32,33,34,35,36,37,38,],[-3,-6,-7,-10,-11,-9,27,-1,-2,-4,-5,-8,-13,-16,-20,-21,-12,-19,38,-14,-15,-17,-18,-22,]),'MUL':([2,4,5,6,7,13,16,17,18,19,20,21,23,24,25,27,32,34,35,36,37,38,],[11,-6,-7,-10,-11,-9,11,11,-4,-5,-8,30,-16,-20,-21,-12,-19,30,30,-17,-18,-22,]),'DIV':([2,4,5,6,7,13,16,17,18,19,20,21,23,24,25,27,32,34,35,36,37,38,],[12,-6,-7,-10,-11,-9,12,12,-4,-5,-8,31,-16,-20,-21,-12,-19,31,31,-17,-18,-22,]),'POW':([5,6,7,13,27,],[14,-10,-11,-9,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,8,],[1,15,]),'term':([0,8,9,10,],[2,2,16,17,]),'power':([0,8,9,10,11,12,],[4,4,4,4,18,19,]),'unary':([0,3,8,9,10,11,12,],[5,13,5,5,5,5,5,]),'atom':([0,3,8,9,10,11,12,],[6,6,6,6,6,6,6,]),'expNoPow':([14,26,],[20,33,]),'expTerm':([14,26,28,29,],[21,21,34,35,]),'expUnary':([14,22,26,28,29,30,31,],[23,32,23,23,23,36,37,]),'expAtom':([14,22,26,28,29,30,31,],[24,24,24,24,24,24,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr ADD term','expr',3,'p_expr_add','calc.py',111),
  ('expr -> expr SUB term','expr',3,'p_expr_sub','calc.py',117),
  ('expr -> term','expr',1,'p_expr_term','calc.py',123),
  ('term -> term MUL power','term',3,'p_term_mul','calc.py',128),
  ('term -> term DIV power','term',3,'p_term_div','calc.py',134),
  ('term -> power','term',1,'p_term_power','calc.py',145),
  ('power -> unary','power',1,'p_power_unary','calc.py',151),
  ('power -> unary POW expNoPow','power',3,'p_power_pow','calc.py',155),
  ('unary -> SUB unary','unary',2,'p_unary_neg','calc.py',165),
  ('unary -> atom','unary',1,'p_unary_atom','calc.py',173),
  ('atom -> NUM','atom',1,'p_atom_num','calc.py',179),
  ('atom -> LPAREN expr RPAREN','atom',3,'p_atom_paren','calc.py',185),
  ('expNoPow -> expTerm','expNoPow',1,'p_expNoPow_term','calc.py',192),
  ('expNoPow -> expNoPow ADD expTerm','expNoPow',3,'p_expNoPow_add','calc.py',196),
  ('expNoPow -> expNoPow SUB expTerm','expNoPow',3,'p_expNoPow_sub','calc.py',202),
  ('expTerm -> expUnary','expTerm',1,'p_expTerm_unary','calc.py',209),
  ('expTerm -> expTerm MUL expUnary','expTerm',3,'p_expTerm_mul','calc.py',213),
  ('expTerm -> expTerm DIV expUnary','expTerm',3,'p_expTerm_div','calc.py',219),
  ('expUnary -> SUB expUnary','expUnary',2,'p_expUnary_neg','calc.py',231),
  ('expUnary -> expAtom','expUnary',1,'p_expUnary_atom','calc.py',237),
  ('expAtom -> NUM','expAtom',1,'p_expAtom_num','calc.py',242),
  ('expAtom -> LPAREN expNoPow RPAREN','expAtom',3,'p_expAtom_paren','calc.py',248),
]
